[PHP]
extension_dir="C:/Axumera-Enginnering/native/dev-runtime/runtime/php/ext"
extension=pdo_mysql
extension=mbstring
extension=openssl
extension=fileinfo
date.timezone=Africa/Addis_Ababa
display_errors=Off
log_errors=On
error_log="C:/Axumera-Enginnering/native/dev-runtime/logs/php-runtime-error.log"
session.save_path="C:/Axumera-Enginnering/native/dev-runtime/application/eaes_exam_system/storage/sessions"
session.use_strict_mode=1
session.cookie_httponly=1
upload_tmp_dir="C:/Axumera-Enginnering/native/dev-runtime/data/tmp"
upload_max_filesize=40M
post_max_size=40M
expose_php=Off
