<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-08-01 22:27:05              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 require_once __DIR__ . '/../app/Autoload.php'; $GLOBALS['__eaes_config'] = require __DIR__ . '/../app/config.php'; if (!function_exists('B_k5T')) { function B_k5T(string $CmSTM, mixed $Ctd3t = null): mixed { $OiBMF = explode('.', $CmSTM); $B2kgN = $GLOBALS['__eaes_config']; foreach ($OiBMF as $CdGbx) { if (!(!is_array($B2kgN) || !array_key_exists($CdGbx, $B2kgN))) { goto ZNu5p; } return $Ctd3t; ZNu5p: $B2kgN = $B2kgN[$CdGbx]; YIUyE: } WRXmx: return $B2kgN; } } if (!(php_sapi_name() !== 'cli')) { goto bO8lW; } die("This script must be run from the command line, e.g.:\n  php database/migrate_legacy.php eaes_exam_old\n"); bO8lW: $D4n1B = $argv[1] ?? null; if ($D4n1B) { goto CV6Wh; } die("Usage: php database/migrate_legacy.php <old_database_name>\n"); CV6Wh: $ZcaZs = B_K5t('db'); $p5qae = App\Core\Database::connection(); $vw54c = App\Core\Database::connectWith($ZcaZs['host'], $ZcaZs['port'], $D4n1B, $ZcaZs['user'], $ZcaZs['pass'], $ZcaZs['charset']); echo "Connected to old database '{$D4n1B}' and new database '{$ZcaZs['name']}'.\n"; $BYbpY = 0; foreach ($vw54c->query('SELECT * FROM admin_users') as $RmthD) { $dzhGf = $p5qae->prepare('INSERT IGNORE INTO admin_users (username, password_hash, created_at) VALUES (:u, :p, NOW())'); $dzhGf->execute(['u' => $RmthD['username'], 'p' => $RmthD['password']]); $BYbpY++; sWWTe: } u4Q5b: echo "Migrated {$BYbpY} admin user(s).\n"; $Du6Rk = []; $dzhGf = $vw54c->query('SELECT * FROM exams'); $kIbMY = 0; foreach ($dzhGf as $RmthD) { $w41Kq = $p5qae->prepare('INSERT INTO exams (exam_name, duration, stream, is_live, color_theme, json_filename, created_at, updated_at)
                           VALUES (:name, :duration, :stream, :live, :color, :file, NOW(), NOW())'); $w41Kq->execute(['name' => $RmthD['exam_name'], 'duration' => $RmthD['duration'], 'stream' => $RmthD['stream'], 'live' => $RmthD['is_live'] ?? 0, 'color' => $RmthD['color_theme'] ?? '#0062cc', 'file' => $RmthD['json_filename'] ?? 'questions.json']); $Du6Rk[$RmthD['id']] = (int) $p5qae->lastInsertId(); $kIbMY++; E4l17: } algA5: echo "Migrated {$kIbMY} exam(s).\n"; $Rmv18 = 0; $dzhGf = $vw54c->query('SELECT * FROM questions'); foreach ($dzhGf as $RmthD) { if (isset($Du6Rk[$RmthD['exam_id']])) { goto Gq0S3; } goto A7cb6; Gq0S3: $OeYit = ($RmthD['paragraph_text'] ?? '') === 'PASSAGE_BLOCK' ? 1 : 0; $w41Kq = $p5qae->prepare('INSERT INTO questions (exam_id, question_number, is_passage, paragraph_text, question_text, option_a, option_b, option_c, option_d, correct_answer)
                           VALUES (:e, :n, :p, :para, :qt, :a, :b, :c, :d, :corr)'); $w41Kq->execute(['e' => $Du6Rk[$RmthD['exam_id']], 'n' => $RmthD['question_number'], 'p' => $OeYit, 'para' => $RmthD['paragraph_text'], 'qt' => $RmthD['question_text'], 'a' => $RmthD['option_a'], 'b' => $RmthD['option_b'], 'c' => $RmthD['option_c'], 'd' => $RmthD['option_d'], 'corr' => $RmthD['correct_answer']]); $Rmv18++; A7cb6: } oOHsk: echo "Migrated {$Rmv18} question row(s).\n"; $xOopn = 0; $MMcAe = 0; $dzhGf = $vw54c->query('SELECT * FROM students'); foreach ($dzhGf as $RmthD) { $yni28 = $p5qae->prepare('SELECT id FROM students WHERE roll_number = :r AND stream = :s LIMIT 1'); $yni28->execute(['r' => $RmthD['roll_number'], 's' => $RmthD['stream']]); $ii9hU = $yni28->fetchColumn(); if ($ii9hU) { goto Pic8n; } $w41Kq = $p5qae->prepare('INSERT INTO students (full_name, roll_number, stream, section, created_at) VALUES (:n, :r, :s, :sec, NOW())'); $w41Kq->execute(['n' => $RmthD['full_name'], 'r' => $RmthD['roll_number'], 's' => $RmthD['stream'], 'sec' => $RmthD['section']]); $ii9hU = (int) $p5qae->lastInsertId(); $xOopn++; Pic8n: if (!(!empty($RmthD['exam_id']) && isset($Du6Rk[$RmthD['exam_id']]))) { goto nasxI; } $PlpeE = $Du6Rk[$RmthD['exam_id']]; $BhSDG = ($RmthD['status'] ?? '') === 'Submitted' ? 'submitted' : 'in_progress'; $w41Kq = $p5qae->prepare("INSERT IGNORE INTO exam_attempts\n                (student_id, exam_id, answers, flags, score, total_questions, status, started_at, submitted_at)\n                VALUES (:sid, :eid, '{}', '{}', :score, NULL, :status, NOW(), :submitted)"); $w41Kq->execute(['sid' => $ii9hU, 'eid' => $PlpeE, 'score' => $RmthD['score'], 'status' => $BhSDG, 'submitted' => $BhSDG === 'submitted' ? date('Y-m-d H:i:s') : null]); $MMcAe++; nasxI: tkZ7Q: } LXAX2: echo "Migrated {$xOopn} student identity/identities and {$MMcAe} attempt record(s).\n"; echo "Done. Legacy admin passwords will auto-upgrade to bcrypt on next successful login.\n";
