<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-08-01 22:27:05              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 namespace App\Repositories; use App\Core\Database; class ExamRepository { public static function all(): array { return Database::connection()->query('SELECT * FROM exams ORDER BY id DESC')->fetchAll(); } public static function find(int $UBSEx): ?array { $dzhGf = Database::connection()->prepare('SELECT * FROM exams WHERE id = :id LIMIT 1'); $dzhGf->execute(['id' => $UBSEx]); $RmthD = $dzhGf->fetch(); return $RmthD ?: null; } public static function liveExam(): ?array { $RmthD = Database::connection()->query("SELECT * FROM exams WHERE is_live = 1 LIMIT 1")->fetch(); return $RmthD ?: null; } public static function latest(): ?array { $RmthD = Database::connection()->query('SELECT * FROM exams ORDER BY id DESC LIMIT 1')->fetch(); return $RmthD ?: null; } public static function create(array $CDwXr): int { $dzhGf = Database::connection()->prepare('INSERT INTO exams (exam_name, duration, stream, is_live, color_theme, json_filename, shuffle_questions, shuffle_choices, created_at, updated_at)
             VALUES (:name, :duration, :stream, 0, :color, :file, :shuffle_q, :shuffle_c, NOW(), NOW())'); $dzhGf->execute(['name' => $CDwXr['exam_name'], 'duration' => $CDwXr['duration'], 'stream' => $CDwXr['stream'], 'color' => $CDwXr['color_theme'], 'file' => $CDwXr['json_filename'], 'shuffle_q' => !empty($CDwXr['shuffle_questions']) ? 1 : 0, 'shuffle_c' => !empty($CDwXr['shuffle_choices']) ? 1 : 0]); return (int) Database::connection()->lastInsertId(); } public static function updateMeta(int $UBSEx, array $CDwXr): void { $dzhGf = Database::connection()->prepare('UPDATE exams SET exam_name = :name, duration = :duration, stream = :stream, color_theme = :color,
                shuffle_questions = :shuffle_q, shuffle_choices = :shuffle_c, updated_at = NOW() WHERE id = :id'); $dzhGf->execute(['name' => $CDwXr['exam_name'], 'duration' => $CDwXr['duration'], 'stream' => $CDwXr['stream'], 'color' => $CDwXr['color_theme'], 'shuffle_q' => !empty($CDwXr['shuffle_questions']) ? 1 : 0, 'shuffle_c' => !empty($CDwXr['shuffle_choices']) ? 1 : 0, 'id' => $UBSEx]); } public static function updateMetaWithFile(int $UBSEx, array $CDwXr): void { $dzhGf = Database::connection()->prepare('UPDATE exams SET exam_name = :name, duration = :duration, stream = :stream, color_theme = :color, json_filename = :file,
                shuffle_questions = :shuffle_q, shuffle_choices = :shuffle_c, updated_at = NOW() WHERE id = :id'); $dzhGf->execute(['name' => $CDwXr['exam_name'], 'duration' => $CDwXr['duration'], 'stream' => $CDwXr['stream'], 'color' => $CDwXr['color_theme'], 'file' => $CDwXr['json_filename'], 'shuffle_q' => !empty($CDwXr['shuffle_questions']) ? 1 : 0, 'shuffle_c' => !empty($CDwXr['shuffle_choices']) ? 1 : 0, 'id' => $UBSEx]); } public static function setLive(int $UBSEx, bool $eImzd): void { $fVwZF = Database::connection(); $fVwZF->exec('UPDATE exams SET is_live = 0'); if (!$eImzd) { goto My7C7; } $dzhGf = $fVwZF->prepare('UPDATE exams SET is_live = 1 WHERE id = :id'); $dzhGf->execute(['id' => $UBSEx]); My7C7: } public static function delete(int $UBSEx): void { $fVwZF = Database::connection(); $dzhGf = $fVwZF->prepare('DELETE FROM exams WHERE id = :id'); $dzhGf->execute(['id' => $UBSEx]); } public static function submissionCount(int $ugLXG): int { $dzhGf = Database::connection()->prepare('SELECT COUNT(*) FROM exam_attempts WHERE exam_id = :id'); $dzhGf->execute(['id' => $ugLXG]); return (int) $dzhGf->fetchColumn(); } }
