<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  3.0.0   |
    |              on 2026-08-01 22:27:05              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 namespace App\Repositories; use App\Core\Database; class QuestionRepository { public static function forExam(int $ugLXG): array { $dzhGf = Database::connection()->prepare('SELECT * FROM questions WHERE exam_id = :id ORDER BY question_number ASC'); $dzhGf->execute(['id' => $ugLXG]); return $dzhGf->fetchAll(); } public static function countForExam(int $ugLXG): int { $dzhGf = Database::connection()->prepare('SELECT COUNT(*) FROM questions WHERE exam_id = :id AND is_passage = 0'); $dzhGf->execute(['id' => $ugLXG]); return (int) $dzhGf->fetchColumn(); } public static function answerKey(int $ugLXG): array { $dzhGf = Database::connection()->prepare('SELECT question_number, correct_answer FROM questions WHERE exam_id = :id AND is_passage = 0'); $dzhGf->execute(['id' => $ugLXG]); $CmSTM = []; foreach ($dzhGf->fetchAll() as $RmthD) { $CmSTM[(int) $RmthD['question_number']] = strtolower(trim((string) $RmthD['correct_answer'])); SckXb: } Mg9Bx: return $CmSTM; } public static function deleteForExam(int $ugLXG): void { $dzhGf = Database::connection()->prepare('DELETE FROM questions WHERE exam_id = :id'); $dzhGf->execute(['id' => $ugLXG]); } public static function bulkInsert(int $ugLXG, array $yesds): void { $fVwZF = Database::connection(); $dzhGf = $fVwZF->prepare('INSERT INTO questions
                (exam_id, question_number, is_passage, paragraph_text, question_text, option_a, option_b, option_c, option_d, correct_answer)
             VALUES
                (:exam_id, :qnum, :is_passage, :paragraph, :text, :a, :b, :c, :d, :correct)'); $WW_Ec = 1; $PiB7y = 0; foreach ($yesds as $lP4Lg) { if (($lP4Lg['type'] ?? '') === 'passage') { $PiB7y++; } } $Rw3Ec = 0; $WW_Ec = 1; foreach ($yesds as $lP4Lg) { if (($lP4Lg['type'] ?? '') === 'passage') { goto GArzq; } $dzhGf->execute(['exam_id' => $ugLXG, 'qnum' => $lP4Lg['question_number'] ?: $WW_Ec, 'is_passage' => 0, 'paragraph' => $lP4Lg['paragraph_text'], 'text' => $lP4Lg['question_text'], 'a' => $lP4Lg['option_a'], 'b' => $lP4Lg['option_b'], 'c' => $lP4Lg['option_c'], 'd' => $lP4Lg['option_d'], 'correct' => $lP4Lg['correct_answer']]); goto gKwh2; GArzq: $dzhGf->execute(['exam_id' => $ugLXG, 'qnum' => -$PiB7y + $Rw3Ec, 'is_passage' => 1, 'paragraph' => 'PASSAGE_BLOCK', 'text' => $lP4Lg['content'], 'a' => $lP4Lg['id'], 'b' => '', 'c' => '', 'd' => '', 'correct' => '']); $Rw3Ec++; gKwh2: $WW_Ec++; bEIBt: } jXqcd: } }
