[CmdletBinding()]
param(
    [string]$TargetVersion = '1.1.0',
    [string]$MinSupportedVersion = '1.0.0'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$source = Join-Path $root 'new_update\eaes_exam_system_protected'
if (!(Test-Path -LiteralPath $source)) { throw "new_update source not found: $source" }

$outDir = Join-Path $root 'build\update-axe11'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

Write-Host "Building Axumera_Update.exe (AXE $TargetVersion) from new_update source..."
Write-Host "Source: $source"

# ---------------------------------------------------------------------------
# 1. Scan the authoritative source and classify every file.
#    Persistent customer state and dev/test artifacts are NEVER shipped:
#      .env, storage/** (license, lock, cache, logs, sessions, backups),
#      tests/**, desktop.ini, yakpro-po.cnf
# ---------------------------------------------------------------------------
function Test-Shipped([string]$rel) {
    if ($rel -eq '.env') { return $false }
    if ($rel -eq 'desktop.ini' -or $rel -eq 'yakpro-po.cnf') { return $false }
    foreach ($prefix in @('storage/', 'tests/')) {
        if ($rel.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) { return $false }
    }
    return $true
}

$shipped = @()
$excluded = @()
Get-ChildItem -Recurse -File -LiteralPath $source | ForEach-Object {
    $rel = $_.FullName.Substring($source.Length + 1).Replace('\', '/')
    if (Test-Shipped $rel) {
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant()
        $shipped += [pscustomobject]@{ Path = $rel; Sha256 = $hash }
    } else {
        $excluded += $rel
    }
}

if ($shipped.Count -eq 0) { throw 'No shipable files found in the new_update source.' }

Write-Host "  shipped files: $($shipped.Count)"
Write-Host "  excluded (preserved / never shipped): $($excluded.Count)"

# ---------------------------------------------------------------------------
# 2. Emit the embedded manifest as C# source (BOM-free).
# ---------------------------------------------------------------------------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Auto-generated by scripts/build-axumera-update11.ps1 - DO NOT EDIT')
[void]$sb.AppendLine('internal static class AxumeraUpdateManifest')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    public const string Product = "Axumera Exam Suite";')
[void]$sb.AppendLine("    public const string TargetVersion = `"$TargetVersion`";")
[void]$sb.AppendLine("    public const string MinSupportedVersion = `"$MinSupportedVersion`";")
[void]$sb.AppendLine('    public static readonly string[][] Files = new string[][] {')
foreach ($f in $shipped) {
    [void]$sb.AppendLine('        new string[] { "' + $f.Path + '", "' + $f.Sha256 + '" },')
}
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

$manifestCs = Join-Path $outDir 'AxumeraUpdateManifest.cs'
[System.IO.File]::WriteAllText($manifestCs, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Manifest generated: $manifestCs ($($shipped.Count) files)"

# ---------------------------------------------------------------------------
# 3. Compile the updater (WinForms GUI + --auto mode).
# ---------------------------------------------------------------------------
$csc = 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (!(Test-Path -LiteralPath $csc)) { throw 'Microsoft .NET Framework C# compiler was not found.' }

$output = Join-Path $outDir 'Axumera_Update.exe'
$srcCs = Join-Path $root 'controller\AxumeraUpdate11.cs'

& $csc /nologo /target:winexe /r:System.Windows.Forms.dll /r:System.Drawing.dll /out:$output $srcCs $manifestCs
if ($LASTEXITCODE -ne 0) { throw 'AxumeraUpdate11 compilation failed.' }
Write-Host "Compiled: $output"

# ---------------------------------------------------------------------------
# 4. Deliver the final executable.
#    - new_update\Axumera_Update.exe  (authoritative deliverable; the only
#      generated file allowed in the source folder)
#    - distribution\Axumera_Update.exe (release copy)
# ---------------------------------------------------------------------------
$newUpdateExe = Join-Path $root 'new_update\Axumera_Update.exe'
Copy-Item -Force -LiteralPath $output -Destination $newUpdateExe
Write-Host "Delivered: $newUpdateExe"

$distExe = Join-Path $root 'distribution\Axumera_Update.exe'
Copy-Item -Force -LiteralPath $output -Destination $distExe
Write-Host "Delivered: $distExe"

$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $newUpdateExe).Hash
Write-Host "SHA-256: $hash"
