<?php
require_once __DIR__ . '/app/bootstrap.php';

use App\Core\Csrf;
use App\Core\Logger;
use App\Core\Validator;
use App\Repositories\AdminRepository;

if (empty($_SESSION['admin_logged_in'])) {
    header('Location: adminlogin.php');
    exit;
}

$error = '';
$notice = '';
$tempPassword = '';
$generatedFor = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!Csrf::verify($_POST['csrf_token'] ?? null)) {
        $error = 'Your session expired. Please try again.';
    } else {
        $action = (string) ($_POST['action'] ?? '');
        $me = (int) ($_SESSION['admin_id'] ?? 0);

        if ($action === 'create_admin') {
            $username = Validator::string($_POST['username'] ?? '', 50);
            $fullName = Validator::string($_POST['full_name'] ?? '', 100);
            $password = (string) ($_POST['password'] ?? '');

            if (strlen($username) < 3) {
                $error = 'Username must be at least 3 characters.';
            } elseif ($password !== '' && (strlen($password) < 8 || strlen($password) > 72)) {
                $error = 'Password must be between 8 and 72 characters.';
            } else {
                $autoGenerated = $password === '';
                if ($autoGenerated) {
                    $password = bin2hex(random_bytes(8)); // 16-char temp
                }
                if (AdminRepository::usernameExists($username)) {
                    $error = 'An admin account named "' . htmlspecialchars($username) . '" already exists.';
                } else {
                    $id = AdminRepository::create($username, $password, $fullName);
                    $notice = 'Admin account "' . htmlspecialchars($username) . '" created successfully.';
                    if ($autoGenerated) {
                        $tempPassword = $password;
                        $generatedFor = $username;
                    }
                    Logger::audit('admin', $_SESSION['admin_username'] ?? '', 'admin_created', [
                        'new_admin_id' => $id,
                        'username' => $username,
                        'full_name' => $fullName,
                    ]);
                }
            }
        } elseif ($action === 'reset_admin_password') {
            $adminId = Validator::int($_POST['admin_id'] ?? 0);
            $admin = $adminId > 0 ? AdminRepository::findById($adminId) : null;
            if (!$admin) {
                $error = 'That admin account no longer exists.';
            } elseif ($adminId === $me) {
                $error = 'You cannot reset your own password here — use Change Password in the top-right menu.';
            } else {
                // Same one-time-temp-password flow as the student reset and the
                // CLI recovery tool: the plaintext is shown once and never logged.
                $tempPassword = bin2hex(random_bytes(8));
                AdminRepository::resetPassword($adminId, $tempPassword); // also clears lockout
                $generatedFor = (string) $admin['username'];
                $wasLocked = (int) $admin['failed_attempts'] > 0
                    || ($admin['locked_until'] !== null && strtotime((string) $admin['locked_until']) > time());
                $notice = 'Password reset for "' . htmlspecialchars((string) $admin['username']) . '"'
                    . ($wasLocked ? ' (lockout cleared)' : '') . '.';
                Logger::audit('admin', $_SESSION['admin_username'] ?? '', 'admin_password_reset', [
                    'target_admin_id' => $adminId,
                    'target_username' => (string) $admin['username'],
                ]);
            }
        } elseif ($action === 'delete_admin') {
            $adminId = Validator::int($_POST['admin_id'] ?? 0);
            $admin = $adminId > 0 ? AdminRepository::findById($adminId) : null;
            if (!$admin) {
                $error = 'That admin account no longer exists.';
            } elseif ($adminId === $me) {
                $error = 'You cannot delete your own account while logged in.';
            } elseif (AdminRepository::count() <= 1) {
                $error = 'You cannot delete the last remaining admin account.';
            } else {
                AdminRepository::delete($adminId);
                $notice = 'Deleted admin account "' . htmlspecialchars((string) $admin['username']) . '".';
                Logger::audit('admin', $_SESSION['admin_username'] ?? '', 'admin_deleted', [
                    'target_admin_id' => $adminId,
                    'target_username' => (string) $admin['username'],
                ]);
            }
        } else {
            $error = 'Invalid action.';
        }
    }
}

$admins = AdminRepository::all();
$me = (int) ($_SESSION['admin_id'] ?? 0);
$total = count($admins);
$now = time();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Settings - <?php echo htmlspecialchars(b_K5t('app.name')); ?></title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/admin.css">
    <style>
        .settings-wrap { max-width: 1080px; margin: 0 auto; padding: 28px 20px 60px; }
        .settings-head { display: flex; justify-content: space-between; align-items: flex-end; flex-wrap: wrap; gap: 14px; margin-bottom: 20px; }
        .settings-head h1 { font-size: 22px; margin: 0; color: var(--color-ink); }
        .settings-head p { margin: 4px 0 0; color: var(--color-muted); font-size: 13px; }
        table.admin-table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid var(--color-border); border-radius: 12px; overflow: hidden; }
        table.admin-table th, table.admin-table td { padding: 12px 14px; text-align: left; font-size: 13.5px; border-bottom: 1px solid var(--color-border); }
        table.admin-table th { background: #f8fafc; color: var(--color-muted); font-weight: 600; text-transform: uppercase; font-size: 11.5px; letter-spacing: .4px; }
        table.admin-table tr:last-child td { border-bottom: none; }
        table.admin-table tr:hover td { background: #fafcff; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 11.5px; font-weight: 700; }
        .badge-ok { background: #f0fdf4; color: #166534; border: 1px solid #bbf7d0; }
        .badge-warn { background: #fffbeb; color: #92400e; border: 1px solid #fde68a; }
        .badge-me { background: #eff6ff; color: #1e40af; border: 1px solid #bfdbfe; }
        .temp-pw-box { background: #fffbeb; border: 1px solid #fcd34d; border-radius: 10px; padding: 14px 18px; margin-bottom: 20px; font-size: 14px; }
        .temp-pw-box code { background: #fef3c7; padding: 3px 10px; border-radius: 6px; font-size: 16px; font-weight: 700; letter-spacing: 1px; }
        .reset-form, .delete-form { display: inline; }
        .btn-sm { font-size: 12.5px; padding: 6px 12px; }
        .btn-delete { color: var(--color-danger); border-color: #fecaca; background: #fff; }
        .btn-delete:hover { background: #fef2f2; }
        .row-actions { display: flex; gap: 6px; justify-content: flex-end; }
        .muted-note { color: var(--color-muted); font-size: 12.5px; }
        .modal-body .form-group label { font-weight: 600; font-size: 13px; }
        .pw-help { font-size: 12px; color: var(--color-muted); margin: 4px 0 0; text-align: left; }
    </style>
</head>
<body>
    <div class="page-shell">
    <?php include __DIR__ . '/partials/admin_header.php'; ?>

    <div class="settings-wrap">
        <div class="settings-head">
            <div>
                <h1>Admin Accounts &amp; Settings</h1>
                <p>Create additional admin accounts so one administrator can always rescue another. Resetting another admin's password also clears any failed-attempt lockout. <?php echo (int) $total; ?> account(s) total — use Change Password (top-right) for your own.</p>
            </div>
            <div>
                <button type="button" class="btn btn-primary" onclick="openCreateModal()">＋ Create Admin Account</button>
            </div>
        </div>

        <?php if ($error !== '') { ?>
            <div class="alert alert-error">⚠️ <?php echo htmlspecialchars($error); ?></div>
        <?php } ?>
        <?php if ($notice !== '') { ?>
            <div class="alert alert-success">✅ <?php echo htmlspecialchars($notice); ?></div>
        <?php } ?>
        <?php if ($tempPassword !== '') { ?>
            <div class="temp-pw-box">
                <strong>🔑 Temporary password for <?php echo htmlspecialchars($generatedFor); ?></strong><br>
                <code><?php echo htmlspecialchars($tempPassword); ?></code><br>
                <span class="muted-note">Give this to the admin in private. It is shown only once; they can change it any time from the top-right menu → Change Password.</span>
            </div>
        <?php } ?>

        <div class="card" style="padding:0;">
            <table class="admin-table">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Full Name</th>
                        <th>Role</th>
                        <th>Status</th>
                        <th>Last Login</th>
                        <th>Created</th>
                        <th style="text-align:right;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!$admins) { ?>
                        <tr><td colspan="7" class="muted-note" style="padding:24px;text-align:center;">No admin accounts found.</td></tr>
                    <?php } ?>
                    <?php foreach ($admins as $a) { ?>
                        <?php $isMe = (int) $a['id'] === $me; ?>
                        <?php $locked = $a['locked_until'] !== null && strtotime((string) $a['locked_until']) > $now; ?>
                        <tr>
                            <td><strong><?php echo htmlspecialchars((string) $a['username']); ?></strong><?php if ($isMe) { ?> <span class="badge badge-me">you</span><?php } ?></td>
                            <td><?php echo htmlspecialchars((string) ($a['full_name'] ?: '—')); ?></td>
                            <td class="muted-note"><?php echo htmlspecialchars((string) ($a['role'] ?: 'admin')); ?></td>
                            <td>
                                <?php if ($locked) { ?>
                                    <span class="badge badge-warn">Locked</span>
                                <?php } elseif ((int) $a['failed_attempts'] > 0) { ?>
                                    <span class="badge badge-warn"><?php echo (int) $a['failed_attempts']; ?> failed attempt(s)</span>
                                <?php } else { ?>
                                    <span class="badge badge-ok">Active</span>
                                <?php } ?>
                            </td>
                            <td class="muted-note"><?php echo $a['last_login_at'] ? htmlspecialchars(date('M j, Y g:i A', strtotime((string) $a['last_login_at']))) : '—'; ?></td>
                            <td class="muted-note"><?php echo $a['created_at'] ? htmlspecialchars(date('M j, Y g:i A', strtotime((string) $a['created_at']))) : '—'; ?></td>
                            <td>
                                <?php if ($isMe) { ?>
                                    <div class="row-actions"><span class="muted-note">—</span></div>
                                <?php } else { ?>
                                    <div class="row-actions">
                                        <form class="reset-form" method="POST" action="admin_settings.php"
                                              data-name="<?php echo htmlspecialchars((string) $a['username'], ENT_QUOTES); ?>">
                                            <?php echo Csrf::field(); ?>
                                            <input type="hidden" name="action" value="reset_admin_password">
                                            <input type="hidden" name="admin_id" value="<?php echo (int) $a['id']; ?>">
                                            <button type="submit" class="btn btn-muted btn-sm">🔑 Reset password</button>
                                        </form>
                                        <form class="delete-form" method="POST" action="admin_settings.php"
                                              data-name="<?php echo htmlspecialchars((string) $a['username'], ENT_QUOTES); ?>">
                                            <?php echo Csrf::field(); ?>
                                            <input type="hidden" name="action" value="delete_admin">
                                            <input type="hidden" name="admin_id" value="<?php echo (int) $a['id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-delete">🗑 Delete</button>
                                        </form>
                                    </div>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Create Admin modal -->
    <div class="modal-background" id="create-admin-modal">
        <div class="modal-card">
            <div class="modal-header">
                <span>＋ Create Admin Account</span>
                <span class="modal-close-btn" onclick="closeCreateModal()">×</span>
            </div>
            <div class="modal-body">
                <p class="muted-note" style="margin-top:0;">A second admin is the best protection against being locked out of the system entirely. The new account can log in at <code>adminlogin.php</code>.</p>
                <form method="POST" action="admin_settings.php">
                    <?php echo Csrf::field(); ?>
                    <input type="hidden" name="action" value="create_admin">
                    <div class="form-group">
                        <label for="af-username">Username</label>
                        <input type="text" id="af-username" name="username" class="form-control" placeholder="e.g. examco2" minlength="3" maxlength="50" required autocomplete="off">
                        <p class="pw-help">At least 3 characters. This is what the admin types to log in.</p>
                    </div>
                    <div class="form-group">
                        <label for="af-fullname">Full Name <span class="muted-note">(optional)</span></label>
                        <input type="text" id="af-fullname" name="full_name" class="form-control" placeholder="e.g. Abebe Kebede" maxlength="100">
                    </div>
                    <div class="form-group">
                        <label for="af-password">Password <span class="muted-note">(optional)</span></label>
                        <input type="text" id="af-password" name="password" class="form-control" placeholder="Leave blank to auto-generate" minlength="8" maxlength="72" autocomplete="off">
                        <p class="pw-help">At least 8 characters. Leave blank and a random temporary password will be generated and shown once after saving.</p>
                    </div>
                    <button type="submit" class="btn btn-primary" style="width:100%;">Create Admin Account</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        function openCreateModal() {
            document.getElementById('create-admin-modal').style.display = 'flex';
        }
        function closeCreateModal() {
            document.getElementById('create-admin-modal').style.display = 'none';
        }
        document.getElementById('create-admin-modal').addEventListener('click', function (e) {
            if (e.target === this) closeCreateModal();
        });

        // Safe confirm dialogs — usernames travel in data-* attributes (HTML-escaped),
        // never inside JS strings.
        document.querySelectorAll('.reset-form').forEach(function (form) {
            form.addEventListener('submit', function (e) {
                var ok = confirm("Reset the password for admin \"" + form.dataset.name + "\"? A one-time temporary password will be generated (and any login lockout cleared).");
                if (!ok) e.preventDefault();
            });
        });
        document.querySelectorAll('.delete-form').forEach(function (form) {
            form.addEventListener('submit', function (e) {
                var ok = confirm("PERMANENTLY delete the admin account \"" + form.dataset.name + "\"? This cannot be undone.");
                if (!ok) e.preventDefault();
            });
        });
    </script>
    <?php include __DIR__ . '/partials/copyright_footer.php'; ?>
    </div>
</body>
</html>
